name: Deploy Parking Manager

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOSTIP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEYPARKING }}
          command_timeout: 20m

          script: |

            set -e

            echo "=================================="
            echo "Starting Deployment"
            echo "=================================="

            cd /home/ubuntu/parking-manager

            echo "Pulling latest code..."

            git fetch origin main
            git reset --hard origin/main

            echo "Creating MongoDB environment..."

            cat > .env <<EOF
            MONGO_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USERNAME }}
            MONGO_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}
            MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
            MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}
            EOF

            echo "Creating server environment..."

            cat > server/.env <<EOF
            PORT=5000
            MONGODB_URI=mongodb://${{ secrets.MONGO_USERNAME }}:${{ secrets.MONGO_PASSWORD }}@mongodb:27017/${{ secrets.MONGO_DATABASE }}?authSource=${{ secrets.MONGO_DATABASE }}
            CLIENT_URL=http://${{ secrets.EC2_HOSTIP }}
            EOF

            echo "Stopping old containers..."

            docker compose down

            echo "Building Docker images..."

            docker compose build

            echo "Starting containers..."

            docker compose up -d

            echo "Cleaning unused images..."

            docker image prune -f

            echo "Checking containers..."

            docker compose ps

            echo "=================================="
            echo "Deployment Completed"
            echo "=================================="
